import type { Metadata } from "next";
import { IBM_Plex_Sans_Arabic } from "next/font/google";
import Navbar from "../../components/ui/navbar/Navbar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Task Interview",
  description: "Generated by create next app",
};
const ibmPlexSansArabic = IBM_Plex_Sans_Arabic({
  subsets: ["arabic"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" lang="ar">
      <head></head>
      <body
        className={`${ibmPlexSansArabic.className}   !bg-[#FAFAFA] text-black`}
      >
        <div className="container">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
